spring:
  rls:
    enabled: true
  application:
    name: auth-service


  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/auth}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:admin}

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.format_sql: true

  flyway:
    enabled: true
    user: ${FLYWAY_USER}
    password: ${FLYWAY_PASSWORD}


server:
  port: ${SERVER_PORT:8085}



eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_DEFAULT_ZONE:http://eureka-service:8761/eureka}
    register-with-eureka: true
    fetch-registry: false


#--- custom jwt secret config ----
security:
  jwt:
    secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
    expiration-time: 86400000 # 1 day
