-- Create databases
CREATE DATABASE orders;
CREATE DATABASE inventory;
CREATE DATABASE menu;
CREATE DATABASE finance;
CREATE DATABASE invoice;
CREATE DATABASE auth;

-- Create app user
CREATE USER app_user WITH PASSWORD 'AppUser@1234';

-- Grant connect privileges to each database
GRANT CONNECT ON DATABASE orders TO app_user;
GRANT CONNECT ON DATABASE inventory TO app_user;
GRANT CONNECT ON DATABASE menu TO app_user;
GRANT CONNECT ON DATABASE finance TO app_user;
GRANT CONNECT ON DATABASE invoice TO app_user;
GRANT CONNECT ON DATABASE auth TO app_user;

-- You need to run schema grants per database
-- PostgreSQL init script runs in the default 'postgres' db context
-- So use \c to switch databases

\c orders
GRANT USAGE ON SCHEMA public TO app_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO app_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO app_user;

\c inventory
GRANT USAGE ON SCHEMA public TO app_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO app_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO app_user;

\c menu
GRANT USAGE ON SCHEMA public TO app_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO app_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO app_user;

\c finance
GRANT USAGE ON SCHEMA public TO app_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO app_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO app_user;

\c invoice
GRANT USAGE ON SCHEMA public TO app_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO app_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO app_user;

\c auth
GRANT USAGE ON SCHEMA public TO app_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO app_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO app_user;