spring:
  application:
    name: finance-service

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/finance}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:admin}

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate.format_sql: true

server:
  port: ${SERVER_PORT:8081}

app:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    topics:
      purchase-event: PURCHASE_EVENT
      invoice-event: INVOICE_EVENT
    groups:
      finance-group: finance-group-consumer



eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_DEFAULT_ZONE:http://eureka-service:8761/eureka}
    register-with-eureka: true
    fetch-registry: false


logging:
  level:
    root: info
    com.sts: debug
  file:
    name: logs/finance.log
