spring:
  rls:
    enabled: true
  application:
    name: finance-service

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true
    user: ${FLYWAY_USER}
    password: ${FLYWAY_PASSWORD}
    locations:
      - classpath:db/migration
      - classpath:db/common-migration

server:
  port: ${SERVER_PORT:8081}



eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_DEFAULT_ZONE}
    register-with-eureka: true
    fetch-registry: false


# Custom application properties
app:
  security:
    gateway-secret: ${GATEWAY_SECRET}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    topics:
      purchase-event: ${PURCHASE_EVENT}
      invoice-event: ${INVOICE_EVENT}
    groups:
      finance-group: finance-group-consumer

