spring:
  rls:
    enabled: true
  application:
    name: order-service

  flyway:
    enabled: true
    user: ${FLYWAY_USER}
    password: ${FLYWAY_PASSWORD}
    locations:
      - classpath:db/migration
      - classpath:db/migration/common

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update


server:
  port: ${SERVER_PORT}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_DEFAULT_ZONE}
    register-with-eureka: true
    fetch-registry: false

# Custom application properties
app:
  security:
    gateway-secret: ${GATEWAY_SECRET}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    groups:
      order-group: order-group-consumer
    topics:
      order-event: ${ORDER_EVENT}
      invoice-event: ${INVOICE_EVENT}
  clients:
    menu-service:
      url: ${MENU_SERVICE_URL}



