spring:
  rls:
    enabled: true
  application:
    name: invoice-service

  flyway:
    enabled: true
    user: ${FLYWAY_USER}
    password: ${FLYWAY_PASSWORD}
    locations:
      - classpath:db/migration
      - classpath:db/migration/common

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/invoice}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:admin}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true

server:
  port: ${SERVER_PORT:8084}

app:
  security:
    gateway-secret: sts@123_gateway_pass_#$%^&*validated_by_aayush+ghimire077@something.sts.com.test&&%secret
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    topics:
      order-event: ORDER_EVENT
      invoice-event: INVOICE_EVENT
    groups:
      invoice-group: invoice-group-consumer
  clients:
    menu-service:
      url: ${MENU_SERVICE_URL:http://localhost:8082}



eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_DEFAULT_ZONE:http://eureka-service:8761/eureka}
    register-with-eureka: true
    fetch-registry: false
