spring:

  rls:
    enabled: true

  flyway:
    enabled: true
    user: ${FLYWAY_USER}
    password: ${FLYWAY_PASSWORD}
    locations:
      - classpath:db/migration
      - classpath:db/common-migration

  application:
    name: inventory-service

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate

server:
  port: ${SERVER_PORT:8080}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_DEFAULT_ZONE}
    register-with-eureka: true
    fetch-registry: false

# Custom application properties
app:
  security:
    gateway-secret: ${GATEWAY_SECRET}

  clients:
    menu-service:
      url: ${MENU_SERVICE_URL}

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}

    topics:
      purchase-event: ${PURCHASE_EVENT}
      invoice-event: ${INVOICE_EVENT}
      stock-event: ${STOCK_EVENT}
    groups:
      inventory-group: inventory-group-consumer


logging:
  level:
    root: INFO
    com.sts: DEBUG

