spring:
  rls:
    enabled: true

  flyway:
    enabled: true
    user: ${FLYWAY_USER}
    password: ${FLYWAY_PASSWORD}
    locations:
      - classpath:db/migration
      - classpath:db/migration/common
  application:
    name: menu-service

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/menu}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:admin}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: ${SERVER_PORT:8082}

app:
  security:
    gateway-secret: sts@123_gateway_pass_#$%^&*validated_by_aayush+ghimire077@something.sts.com.test&&%secret
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    topics:
      stock-event: STOCK_EVENT
    groups:
      menu-service-group: menu-service-group



eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_DEFAULT_ZONE:http://eureka-service:8761/eureka}
    register-with-eureka: true
    fetch-registry: false